image:
  repository: ${locust_repository}
  tag: ${locust_tag}

master:
  config:
    target-host: ${target_host}

worker:
  replicaCount: ${locust_workers}
  config:
    locust-script: /locust-tasks/${locust_script}

service:
  type: ClusterIP
  name: http-master-web
