require "rake/clean"
require_relative "../../rakefiles/vars.rb"
import "../../rakefiles/kops.rake"

if ENV["RAKE_ENV_SHORT"].nil?
  ENV["RAKE_ENV_SHORT"] = "dev"
end
setup_vars(ENV["RAKE_ENV_SHORT"])

task :default => :generate

task :generate => [@tmpdir, :configure_kops, "Rakefile"] do
  sh "kops delete cluster \
    --yes \
    --name=$TF_VAR_cluster_name \
    --unregister \
    || echo 'kops delete cluster failed, but that is ok.' \
  "
  sh "kops create cluster \
    --name=$TF_VAR_cluster_name \
    --channel=alpha \
    --kubernetes-version=1.7.3 \
    --cloud=aws \
    --zones=us-east-2a,us-east-2b,us-east-2c \
    --node-count=3 \
    --master-zones=us-east-2a,us-east-2b,us-east-2c \
    --node-size=t2.micro \
    --master-size=t2.micro \
    --target=terraform \
    --out=. \
    --ssh-public-key=~/.ssh/id_rsa.gpii-ci.pub
  "
end
CLEAN << "kubernetes.tf"
CLEAN << "data"


# vim: ts=2 sw=2:
