name: gpii-flowmanager
version: 0.0.1
appVersion: 57d0a17da505c8bc28c221c88b8de54447c78dc873c355d0bfd435d28f8b09ee
home: https://github.com/gpii-ops/gpii-infra
description: GPII Flowmanager Service.
icon: https://gpii.net/sites/all/themes/gpii_main/logo.png
keywords:
  - gpii
  - flowmanager
sources:
  - https://github.com/gpii-ops/gpii-infra
maintainers:
  - name: amatas
    email: alfredo@raisingthefloor.org
  - name: natarajaya
    email: sergey@raisingthefloor.org
  - name: mrtyler
    email: tyler@raisingthefloor.org
