{{- if .Values.enableStackdriverTrace }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "flowmanager.name" . }}-googleapis
spec:
  hosts:
  - www.googleapis.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
{{- end }}
