require "rake/clean"
require_relative "../rakefiles/vars.rb"
import "../rakefiles/build.rake"
import "../rakefiles/deploy.rake"

if ENV["RAKE_ENV_SHORT"].nil?
  ENV["RAKE_ENV_SHORT"] = File.basename(File.dirname(__FILE__))
end
setup_vars(ENV["RAKE_ENV_SHORT"])

task :default => :deploy

desc "Create or update cluster"
task :apply => [@tmpdir, :generate_modules] do
  sh "terragrunt apply-all --terragrunt-non-interactive"
  Rake::Task["wait_for_api_dns"].invoke
  puts "Waiting 60s to give local DNS a chance to catch up..."
  sleep 60
  Rake::Task["wait_for_api_dns_local"].invoke
  Rake::Task["test_master"].invoke
end
CLEAN << "#{ENV['HOME']}/.terragrunt"

task :test_master do
  sh "ssh -i ~/.ssh/id_rsa.gpii-ci -o StrictHostKeyChecking=no admin@api.#{ENV["TF_VAR_cluster_name"]} -- ping -c 1 8.8.8.8"
end

desc "Destroy cluster"
task :destroy => [@tmpdir, :generate_modules, :undeploy] do
  Rake::Task["_destroy"].invoke
end

desc "[ADVANCED] Helper for :destroy that ignores dependencies; useful for cleaning up malformed clusters."
task :_destroy => @tmpdir do
  sh "terragrunt destroy-all --terragrunt-non-interactive"
  Rake::Task["kops_delete_cluster"].invoke
  Rake::Task["destroy_prereqs"].invoke
  Rake::Task["clean_modules"].invoke
end


# vim: ts=2 sw=2:
