apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image: quay.io/prometheus/node-exporter:v0.15.0
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: rootfs
          readOnly: true
          mountPropagation: HostToContainer  # Alpha in k8s 1.8; requires kubelet '--feature-gates MountPropagation=true'
          mountPath: /host/rootfs
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
      - name: rootfs
        hostPath:
          path: /
  updateStrategy:
    type: RollingUpdate
