require "erb"
require "rake/clean"
require "yaml"
require_relative "../../rakefiles/vars.rb"

if ENV["RAKE_ENV_SHORT"].nil?
  ENV["RAKE_ENV_SHORT"] = "dev"
end
setup_vars(ENV["RAKE_ENV_SHORT"])

task :default => :generate

DEPLOY_OUT_DIR = "#{@tmpdir}-modules/deploy"
directory DEPLOY_OUT_DIR
CLOBBER << DEPLOY_OUT_DIR

task :setup_versions do
  version_yml = File.read("./version.yml")
  @versions = YAML.load(version_yml)
end

SOURCE_FILES = FileList.new("*.erb")
DEST_FILES = SOURCE_FILES.ext(".yml")
DEST_FILES_WITH_PATH = SOURCE_FILES.ext(".yml").map { |f| File.join(DEPLOY_OUT_DIR, f) }

desc "Generate GPII component configs for cluster"
task :generate => [DEPLOY_OUT_DIR, "Rakefile", :setup_versions] + DEST_FILES do
  cp FileList.new("./*.yml"), "#{DEPLOY_OUT_DIR}/"
end

rule ".yml" => ".erb" do |t|
  rendered = ERB.new(File.read(t.source)).result(binding)
  File.open(File.join(DEPLOY_OUT_DIR, t.name), "w") do |f|
    f.puts rendered
  end
end
CLEAN << DEPLOY_OUT_DIR


# vim: ts=2 sw=2:
