#!/bin/sh

# Whitespace-separated list of pairs of service_name|image_name
COMPONENTS="\
  flow-manager|gpii/universal:latest \
  preferences-dataloader|gpii/preferences-dataloader:latest \
  preferences|gpii/universal:latest \
"

for component in $COMPONENTS ; do
  service_name=$(echo "$component" | awk -F'|' '{print $1}')
  image_name=$(echo "$component" | awk -F'|' '{print $2}')
  docker pull $image_name
  image_sha=$(docker inspect "$image_name" --format '{{ index .RepoDigests 0 }}')
  yaml="$yaml\n$service_name: \"$image_sha\""
done

# Manual YAML construction is silly, but it avoids pulling in a dependency on a yaml library.
echo "# This file is generated by $0." > version.yml
echo "---" >> version.yml
echo "$yaml" | sort >> version.yml
