{{- range $host := .Values.egress.httpsHosts }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-{{ $host | replace "." "-" }}
  labels:
    app: {{ include "istio-gke-helper.name" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: tls-{{ $host | replace "." "-" }}
{{- end }}
