{{- if .Values.egress.httpsHosts }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  labels:
    app: {{ include "istio-gke-helper.name" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    {{- range $host := .Values.egress.httpsHosts }}
    - {{ $host }}
    {{- end }}
    port:
      name: tls-https
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
{{- end }}
