import "../../../common/rakefiles/entrypoint.rake"

@env = File.basename(File.dirname(__FILE__))
@project_type = File.basename(File.expand_path("../../../", __FILE__))

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:test_security) do |t|
    t.rspec_opts = '--format documentation'
  end
rescue LoadError
end

# vim: et ts=2 sw=2:
