import "../../../shared/rakefiles/entrypoint.rake"
import "../../../shared/rakefiles/entrypoint-common.rake"

ENV["ORGANIZATION_ID"] = "327626828918"
ENV["TF_VAR_organization_name"] = "gpii2test"
ENV["TF_VAR_organization_domain"] = "test1.gpii.net"
ENV["TF_VAR_aws_zone_id"] = "Z1T3NF8J9WVBSP"

@env = File.basename(File.dirname(__FILE__))
@project_type = File.basename(File.expand_path("../../../", __FILE__))


# vim: et ts=2 sw=2:
