{{ if not (index .Values.master.config "target-host" | regexMatch ".cluster.local")  }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: locust-target
spec:
  hosts:
  - {{ include "locust.host" . }}
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
{{ end }}
