version: "3.4"

services:
  xk:
    image: gpii/exekube:0.5.1-google_gpii.0
    working_dir: /project
    environment:
      USER: ${USER:?err}
      ENV: ${ENV:?err}
      ORGANIZATION_ID:
      BILLING_ID:
      BILLING_ORGANIZATION_ID:

      TF_INPUT: "0"
      TF_LOG:

      # TF_VAR_project_id is used to create a GCP project for our environment
      #   via the gcp-project-init script
      # It's then used by modules as a space to create resources in
      TF_VAR_project_id:

      # TF_VAR_serviceaccount_key will be used by the gcp-project-init script
      #    to put the service account key upon the creation of the GCP project
      # It can then be used by modules to authenticate to GCP
      # It is being populated in Rake code, only if SA credentials are configured
      TF_VAR_serviceaccount_key:

      # TF_VAR_default_dir is the default directory for Terraform / Terragrunt
      # Used when we run `xk up` or `xk down` without an argument
      TF_VAR_default_dir: /project/live/${ENV}/k8s

      # TF_VAR_secrets_dir is used by multiple modules to source secrets from
      TF_VAR_secrets_dir: /project/live/${ENV}/secrets

      # TF_VAR_charts_dir is the place where common charts live, relative to modules
      TF_VAR_charts_dir: ../../../../../charts

    # File with other environment variables will be populated by rake
    env_file:
      - live/${ENV}/compose.env

    ports:
      - 8001:8001
    volumes:
      - .:/project
      - ../shared/charts:/charts
      - ../shared/rakefiles:/rakefiles
      - secrets:/project/live/${ENV}/secrets
      - helm:/root/.helm
      - gcloud:/root/.config/gcloud
      - kube:/root/.kube
      - aws:/root/.aws

      # EXEKUBE DEVELOPMENT
      # - ../../exekube/modules:/exekube-modules
      # ---
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"

volumes:
  secrets:
    # We add USER -- potentially a second time as TF_VAR_project_id may contain
    # USER already, e.g.  gcp-gpii-dev-mrtyler -- to prevent conflicts when two
    # users (e.g. mrtyler and gitlab-runner) are working on the same
    # environment on the same machine (e.g. the CI worker).
    name: ${TF_VAR_project_id}-${USER}-secrets
  helm:
    name: ${TF_VAR_project_id}-${USER}-helm
  gcloud:
    name: ${TF_VAR_project_id}-${USER}-gcloud
  kube:
    name: ${TF_VAR_project_id}-${USER}-kube
  aws:
    name: ${TF_VAR_project_id}-${USER}-aws

# vim: et ts=2 sw=2:
