{{- if or (not .Values.awsRole)  ( eq .Values.logtype "elasticsearch") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- if eq .Values.logtype "elasticsearch" }}
  elasticsearch_prefix: {{ .Values.elasticsearch.prefix | b64enc | quote }}
  elasticsearch_host: {{ .Values.elasticsearch.host | b64enc | quote }}
  elasticsearch_port: {{ .Values.elasticsearch.port | b64enc | quote }}
  elasticsearch_scheme: {{ .Values.elasticsearch.scheme | b64enc | quote }}
  elasticsearch_user: {{ .Values.elasticsearch.user | b64enc | quote }}
  elasticsearch_password: {{ .Values.elasticsearch.password | b64enc | quote }}
{{- end }}
{{- if eq .Values.logtype "cloudwatch" }}
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end }}
{{- end }}
