controller:
  config:
    server-tokens: "false"
  service:
    loadBalancerIP: ${load_balancer_ip}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

defaultBackend:
  replicaCount: 2

rbac:
  create: true
  serviceAccountName: default
