import "../../../shared/rakefiles/entrypoint.rake"
import "../../../shared/rakefiles/entrypoint_common.rake"

@env = File.basename(File.dirname(__FILE__))
@project_type = File.basename(File.expand_path("../../../", __FILE__))


# vim: et ts=2 sw=2:
